---
title: "Hypha.app"
baseURL: "https://www.hypha.app/"
theme: "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
disableKinds: ["taxonomy", "term"]

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "info@example.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "Submission management software for open calls."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: false
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  mobileMenu: false
  poweredby: false
  realfavicongenerator: true
  safariPinnedColor: "#ffffff"
  sidebar: false
  submitted: false
  themeColor: "#ffffff"
