---
title: "Hypha.app"
baseURL: "https://www.hypha.app/"
theme: "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
disableKinds: ["taxonomy", "term"]

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML"]
  section: ["HTML"]

params:
  contact: "hello@@hypha.app"
  copyright: "Copyright (©) 2022 - Open Technology Fund"
  description: "Hypha is an open source submission management platform to receive and manage applications for funding."
  dateformat: "2 January, 2006"
  favicon: "logo.png"
  feedlinks: false
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "logo.png"
  image: "logo.png"
  imageMaxWidth: 400
  mobileMenu: false
  poweredby: false
  realfavicongenerator: true
  safariPinnedColor: "#ffffff"
  sidebar: false
  submitted: false
  themeColor: "#ffffff"
